{{- $Values := $.Values.redis.custom.backup -}}
{{- if $Values.enabled -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-redis-backup
  labels:
    {{- include "ant-media.labels" . | nindent 4 }}
    "app.kubernetes.io/component": "redis"
    {{- with $Values.persistence.labels  }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $Values.persistence.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    {{- range $Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- with (default $Values.persistence.storageClass $.Values.global.storageClass) }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ $Values.persistence.size  }}
{{- end -}}