
{{- $Values := $.Values.redis.custom.backup -}}
{{- if $Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-redis-backup
  labels:
    {{- include "ant-media.labels" . | nindent 4 }}
    "app.kubernetes.io/component": "redis"
{{- end }}
