{{- if .Values.origin.ingress.enabled -}}
{{- $fullName := include "ant-media.fullname" . -}}
{{- if and .Values.origin.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.origin.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.origin.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-origin
  labels:
    {{- include "ant-media.labels" . | nindent 4 }}
    "app.kubernetes.io/component": "origin"
  annotations:
  {{- with .Values.origin.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.origin.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.origin.ingress.className }}
  {{- end }}
  {{- if .Values.origin.ingress.tls }}
  tls:
    - secretName: {{ $fullName }}-origin-tls
      hosts:
      {{- range .Values.origin.ingress.hosts }}
        - {{ . | quote }}
      {{- end }}
  {{- end }}
  rules:
    {{- range .Values.origin.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.origin.ingress.path }}
            {{- if and $.Values.origin.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $.Values.origin.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-origin
                port:
                  number: 5080
              {{- else }}
              serviceName: {{ $fullName }}-origin
              servicePort: 5080
              {{- end }}
    {{- end }}
{{- end }}