kind: Service
apiVersion: v1
metadata:
  name: {{ include "ant-media.fullname" . }}-origin
  labels:
    {{- include "ant-media.labels" . | nindent 4 }}
    "app.kubernetes.io/component": "origin"
spec:
  selector:
    "app.kubernetes.io/component": "origin"
    {{- include "ant-media.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 5080