{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluo.fullname" . }}-update-agent
  labels:
    {{- include "fluo.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "fluo.selectorLabels" . | nindent 6 }}
      app: {{ include "fluo.fullname" . }}-update-agent
  template:
    metadata:
      labels:
        {{- include "fluo.labels" . | nindent 8 }}
        app: {{ include "fluo.fullname" . }}-update-agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fluo.serviceAccountName" . }}
      {{- with .Values.agent.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: update-agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" $.Chart.AppVersion)  }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.agent.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
          - "/bin/update-agent"
        args:
        {{- with .Values.agent.extraArgs }}
          {{- range $key, $value := . }}
        - --{{ $key | mustRegexFind "^[^_]+" }}
          {{- end }}
        {{- end }}
        volumeMounts:
          - mountPath: /var/run/dbus
            name: var-run-dbus
            readOnly: false
          - mountPath: /etc/flatcar
            name: etc-flatcar
            readOnly: true
          - mountPath: /usr/share/flatcar
            name: usr-share-flatcar
            readOnly: true
          - mountPath: /etc/os-release
            name: etc-os-release
            readOnly: true
        env:
          - name: UPDATE_AGENT_NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: var-run-dbus
        hostPath:
          path: /var/run/dbus
      - name: etc-flatcar
        hostPath:
          path: /etc/flatcar
      - name: usr-share-flatcar
        hostPath:
          path: /usr/share/flatcar
      - name: etc-os-release
        hostPath:
          path: /etc/os-release
{{- end }}