{{- if .Values.headplane.plane.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.headplane.plane.secret.name }}
  {{- with .Values.headplane.plane.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.headplane.plane.secret.oidc.client_secret}}
  HEADPLANE_OIDC__CLIENT_SECRET: {{ .Values.headplane.plane.secret.oidc.client_secret | quote }}
  {{- end }}
  {{- if .Values.headplane.plane.secret.oidc.client_id }}
  HEADPLANE_OIDC__CLIENT_ID: {{ .Values.headplane.plane.secret.oidc.client_id | quote }}
  {{- end }}
  {{- if .Values.headplane.plane.secret.oidc.headscale_api_key }}
  HEADPLANE_OIDC__HEADSCALE_API_KEY: {{ .Values.headplane.plane.secret.oidc.headscale_api_key | quote }}
  {{- end }}
  {{- if .Values.headplane.plane.secret.server.cookie_secret }}
  HEADPLANE_SERVER__COOKIE_SECRET: {{ .Values.headplane.plane.secret.server.cookie_secret | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{$.Release.Name}}-headplane-config
stringData:
  config.yaml: |
    {{- toYaml .Values.headplane.plane.config | nindent 4 }}
{{- if .Values.headplane.scale.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.headplane.scale.secret.name }}
  {{- with .Values.headplane.scale.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.headplane.scale.secret.oidc.client_secret}}
  HEADSCALE_OIDC_CLIENT_SECRET: {{ .Values.headplane.scale.secret.oidc.client_secret | quote}}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{$.Release.Name}}-headscale-config
stringData:
  config.yaml: |
    {{- toYaml .Values.headplane.scale.config | nindent 4 }}




