{{ $Values := .Values.headplane.plane.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{$.Release.Name}}-headplane
  labels:
    "app.kubernetes.io/component": "headplane"
    {{- include "helm.labels" $ | nindent 4 }} 
spec:
{{- if (or (eq $Values.type "ClusterIP") (empty $Values.type)) }}
  type: ClusterIP
  {{- if $Values.clusterIP }}
  clusterIP: {{ $Values.clusterIP }}
  {{end}}
{{- else if eq $Values.type "LoadBalancer" }}
  type: {{ $Values.type }}
  {{- if $Values.loadBalancerIP }}
  loadBalancerIP: {{ $Values.loadBalancerIP }}
  {{- end }}
  {{- if $Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml $Values.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{$Values.type }}
{{- end }}
  {{- if $Values.sessionAffinity }}
  sessionAffinity: {{ $Values.sessionAffinity }}
  {{- end }}
  ports:
  - name: headplane
    port: 3000
    protocol: TCP
    targetPort: headplane
    {{ if (and (eq $Values.type "NodePort") (not (empty $Values.nodePort))) }}
      {{- if $Values.nodePort }}
    nodePort: {{$Values.nodePort}}
      {{- end }}
    {{ end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}