name: Bug report
about: Bug reports improve the repo quality
title: '[Bug]: '
labels: [ 'bug' ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: chart
    attributes:
      label: What Chart are you seeing the problem on?
      multiple: true
      options:
        - library
        - csgo
        - tavern
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what did you expect to happen?
      placeholder: A clear and concise description of the result.
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: Expected Result
      description: Tell us what did happen
      placeholder: A clear and concise description of the expected result.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce it
      description: Tell us how we can reproduce it as minimally and precisely as possible.
      placeholder: A clear and concise description of the reproduction.
    validations:
      required: true
  - type: textarea
    id: anything
    attributes:
      label: Anything else we need to know
    validations:
      required: false
