---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{$.Release.Name}}-relay
  namespace: {{$.Release.Namespace}}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{$.Release.Name}}-relay
  namespace: {{$.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{$.Release.Name}}-relay
subjects:
- kind: ServiceAccount
  name: {{$.Release.Name}}-relay
