apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kubeconfig-generators
spec:
  generateExistingOnPolicyUpdate: false
  background: false
  rules:
  - name: kubeconfig-generator
    preconditions:
      any:
      - key: {{ request.object.type }}
        operator: Equals
        value: "kubernetes.io/service-account-token"
    match:
      any:
      - resources:
          kinds:
          - "Secret"
    generate:
      synchronize: true
      apiVersion: v1
      kind: Secret
      name: {{ request.object.metadata.labels.\"kubeconfig.bedag.ch/name\" join('-', [request.object.metadata.name,'kubeconfig'])" }}
      namespace: {{ include "kyverno-policies.printTpl" (printf "%s || request.object.metadata.namespace" $label_namespace) }}
      data: 
        data: {{ include "kyverno-policies.printTpl" "request.object.data" }}