apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hypersciene-crds
  namespace: x16-document-squeezer-hyperscience-prod
subjects:
  - kind: ServiceAccount
    name: x16-document-squeezer-deploy
    namespace: tenants
roleRef:
  kind: Role
  name: hypersciene-crds
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hypersciene-crds
  namespace: x16-document-squeezer-hyperscience-prod
rules:
  - apiGroups: ["hyperscience.net"]
    resources: ["*"]
    verbs: ["get", "watch", "list", "create", "patch", "delete", "deletecollection" ]
  - apiGroups: ["kopf.dev"]
    resources: ["kopfpeerings"]
    verbs: ["list" ,"watch", "patch", "get"]
