{{- with $.Values.prometheus }}
  {{- if and .enabled .service }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubevirt-manager.fullname" $ }}-config
  labels:
    {{- include "kubevirt-manager.labels" $ | nindent 4 }}
data:
  prometheus.conf: |
    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization "";
        proxy_pass_request_body on;
        proxy_pass_request_headers on;
       	client_max_body_size 5g;
       	proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass {{ .service }};
    }
  {{- end }}
{{- end }}