apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-cloudreve
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      {{- if .Values.gateway.sectionName }}
      sectionName: {{ .Values.gateway.sectionName }}
      {{- end }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace }}
      {{- end }}
  hostnames:
    - {{ .Values.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Release.Name }}-cloudreve
          port: {{ .Values.service.port }}