apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cloudreve
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5212
      protocol: TCP
      name: http
  selector:
    app: cloudreve