apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acceleration.fullname" . }}
  labels:
    {{- include "acceleration.labels" . | nindent 4 }}
    {{- with $.Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $.Values.service.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  config.yaml: |-
  {{- $config := default $.Values.config.template $.Values.config.customConfiguration -}}
  {{- $raw := (include "lib.utils.strings.template" (dict "value" $config "context" $)) }}
  {{- $tpl := (fromYaml ($raw)) }}
  {{- if not (include "lib.utils.errors.unmarshalingError" $tpl) }}
    {{- toYaml $tpl | nindent 4 }}
  {{- else -}}
    {{- fail (printf "Found YAML error in config: %s: %s" ($tpl).Error $raw) -}}
  {{- end -}}