apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acceleration.fullname" . }}
  labels:
    {{- include "acceleration.labels" . | nindent 4 }}
    {{- with $.Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $.Values.service.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
