apiVersion: apps/v1
kind: Deployment
metadata:
  name: overwritten
spec:
  minReadySeconds: 100
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: overwritten
      trusted: true
    spec:
      containers:
      - name: sidecar
      - name: backend
        ports:
        - __inject__
        - name: http
          containerPort: 9443
          protocol: UDP
        - name: additonal
          containerPort: 8888
          protocol: TCP
        - name: metrics
          containerPort: 9001
          protocol: TCP
        - __inject__
        - name: http
          containerPort: 10000
        command:
        - __inject__
        - --level=info
        - --cache-server=cache:6379
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 32Mi