---
name: 'PR Labels'
on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@37a5ad4ae20ea8032abf169d953bcd661fd82cd3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
